server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Configuración para SPA (Vue Router en modo history)
    location / {
        try_files  / /index.html;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Configuración para archivos estáticos (assets)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Denegar acceso a archivos ocultos
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}
